services:
  catalog-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./scripts/init_db/init_catalog.sql:/docker-entrypoint-initdb.d/init_catalog.sql
    expose:
      - 5432
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 16686:16686
      - 14268:14268
      - 5775:5775/udp
      - 6832:6832/udp
      - 5778:5778
      - 9411:9411