# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: localhost:5001/catalog
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "catalog"

serviceAccount:
  create: true
  annotations: {}
  name: "catalog"

env:
  normal:
    - name: "JAEGER_HOST"
      value: "http://jaeger-collector"
    - name: "JAEGER_PORT"
      value: 14268
    - name: "DB_CREDENTIALS_PATH"
      value: "/vault/secrets/db-creds"

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "catalog"
  vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/db-app"
  vault.hashicorp.com/agent-inject-template-db-creds: |
    {
    {{ with secret "database/creds/db-app" -}}
    "db_connection": "host=postgre-db-postgresql port=5432 user={{ .Data.username }} password={{ .Data.password }} dbname=catalog sslmode=disable"
    {{- end }}
    }

podSecurityContext:
  runAsUser: 1101
  runAsGroup: 1101

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

tolerations: []

affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80