// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Item defines model for Item.
type Item struct {
	// Unique ID of the item
	Id int64 `json:"id"`

	// Name of the item
	Name *string `json:"name,omitempty"`
}

// NewItem defines model for NewItem.
type NewItem struct {
	// Name of the item
	Name string `json:"name"`
}

// CreateItemJSONBody defines parameters for CreateItem.
type CreateItemJSONBody = NewItem

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = CreateItemJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns all items
	// (GET /v1/items)
	GetItems(ctx echo.Context) error
	// Create new item
	// (POST /v1/items)
	CreateItem(ctx echo.Context) error
	// Removes an item by ID
	// (DELETE /v1/items/{id})
	DeleteItemByID(ctx echo.Context, id int64) error
	// Returns an item by ID
	// (GET /v1/items/{id})
	FindItemByID(ctx echo.Context, id int64) error
	// Updates an item by ID
	// (PUT /v1/items/{id})
	UpdateItemByID(ctx echo.Context, id int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetItems converts echo context to params.
func (w *ServerInterfaceWrapper) GetItems(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetItems(ctx)
	return err
}

// CreateItem converts echo context to params.
func (w *ServerInterfaceWrapper) CreateItem(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateItem(ctx)
	return err
}

// DeleteItemByID converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteItemByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteItemByID(ctx, id)
	return err
}

// FindItemByID converts echo context to params.
func (w *ServerInterfaceWrapper) FindItemByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindItemByID(ctx, id)
	return err
}

// UpdateItemByID converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateItemByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateItemByID(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/v1/items", wrapper.GetItems)
	router.POST(baseURL+"/v1/items", wrapper.CreateItem)
	router.DELETE(baseURL+"/v1/items/:id", wrapper.DeleteItemByID)
	router.GET(baseURL+"/v1/items/:id", wrapper.FindItemByID)
	router.PUT(baseURL+"/v1/items/:id", wrapper.UpdateItemByID)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8SVT2/bPAzGv4rA9z0adboVO/jYBht86WFDT0UOqk07Gqw/peQURqDvPkiy09ZOtqwo",
	"ukvdMBb58MeHyh4qLY1WqJyFYg+22qLk8d/SoQxPQ9ogOYExKurwt0ZbkTBOaAUF3Cnx2CMr10w3zG2R",
	"iXA0g0aT5A4KEMp9uYIM3GAwfcQWCXwGiktcJrzlEme5xqPWkVAteJ8B4WMvCGso7oOqjc/gFp+Oq36n",
	"MjHNxoewUI1eZvyBtBMVMkJrtLLioUPWaGKSK94K1bKKO97pNpazoZ5wXSh4k+KQwQ7JpmSXF6uLVYCk",
	"DSpuBBTwOYYyMNxtY2P57jJPuYo9tOiWkr6j60lZxlUqyhrSMrY8armAWIF4OFDWUMA3dOWob2wkUfy0",
	"WoVHpZVDFUtxYzpRxZP5TxvqTRaKXpmE/U/YQAH/5c9my0en5XFg/kCeE/EBIuLXfURFE1iMo7G9lJyG",
	"l0123YjWZ2C0PcLjhpA7PPBgQp0Gkd4tkzWCEdC6a10Pf0Xhd81PhvWvneaoR7+Af/luZZ9rLhmfQpxY",
	"MIVPaVfCtwf35XtR+8S6Q3dk1dYxbhPyuQPZA7dYM61isFwz24fWsF4MJKUJMq+Hch0XgbhEh2ShuJ8X",
	"TRfSNGin2agubC8UcYlguoLCFTIfQfYC5x/vMr9ZDOxqySESTjLqhYel3r0w5sPAynXw8TlrfcZWfxWq",
	"fjO5Bl21/TBwq3/q9DnawyBMf2QQd6Y+cZ+cb+uU483D6ePxj53OEZxJxtzWcz4jzfgS0m5qsacOCsjD",
	"z5zf+F8BAAD//wfyuIWXCAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
