openapi: "3.0.0"
info:
  version: 1.0.0
  title: Catalog
  description: Service responsible for managing catalog items
servers:
  - url: /api
paths:
  /v1/items:
    get:
      summary: Returns all items
      operationId: getItems
      description: Returns an items from the catalog.
      responses:
        200:
          description: Items response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      summary: Create new item
      operationId: createItem
      description: Creates an item in catalog.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewItem'
      responses:
        201:
          description: Item response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  /v1/items/{id}:
    get:
      summary: Returns an item by ID
      operationId: findItemByID
      description: Returns an item from the catalog.
      parameters:
        - name: id
          in: path
          description: ID of an item to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Item response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    delete:
      summary: Removes an item by ID
      operationId: deleteItemByID
      description: Deletes item from the catalog based on the ID supplied
      parameters:
        - name: id
          in: path
          description: ID of an item to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: Item deleted
    put:
      summary: Updates an item by ID
      operationId: updateItemByID
      description: Updates an item in catalog based on the ID supplied
      parameters:
        - name: id
          in: path
          description: ID of an item to update
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Item updated
components:
  schemas:
    NewItem:
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the item
    Item:
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          description: Unique ID of the item
        name:
          type: string
          description: Name of the item